# -*- coding: utf-8 -*-
"""Codex1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y3cA9S864cC2oTYsWHBci7pcFl3dG9Dg
"""

import streamlit as st
import pandas as pd
import requests
import matplotlib.pyplot as plt

# Título de la aplicación
st.title('Aplicación Web: Datos desde una API REST')
# URL de la API REST (puedes cambiarla por cualquier API pública que devuelva JSON)
api_url = 'https://restcountries.com/v3.1/all'
# Realizar la petición a la API
response = requests.get(api_url)
# Verificar que la respuesta sea exitosa (código 200)

if response.status_code == 200:
    # Convertir los datos JSON en un DataFrame de Pandas
    data = response.json()
    df = pd.DataFrame(data)
    # Mostrar los primeros registros
    st.write('Datos obtenidos de la API:')
    st.write(df.head())
    # Seleccionar una columna para mostrar en Streamlit
    columnas = st.multiselect('Selecciona las columnas a visualizar',
    df.columns.tolist(), default=df.columns.tolist())
    df_seleccionado = df[columnas]
    # Mostrar el DataFrame con las columnas seleccionadas
    st.write('Datos seleccionados:')
    st.write(df_seleccionado)
    # Filtro por ID
    id_filtro = st.slider('Filtrar por ID (entre 1 y 100)', 1, 100, 50)
    df_filtrado = df[df['id'] <= id_filtro]
    st.write(f'Mostrando datos donde ID <= {id_filtro}:')
    st.write(df_filtrado)

else:
 st.error('Error al obtener los datos de la API')
